### ISSUE TITLE
Change Log text not visible with Black color theme; plugin's Settings page is blank

### ISSUE THREAD

**Issue by benfishbus** [phyzical/docker.versions#3]
I'm using Dynamix color theme "Black" on 6.12.13, and the change log windows created by the plugin contain barely readable black text. I also can't see anything on the Settings page for docker.versions

**Comment by phyzical** [comment]
hey are you referring to this one?

Just trying to replicate to see what i can do about it

![image](https://github.com/user-attachments/assets/906261e0-136e-431a-b667-2764a415216d)

this doesn't seem to ever change anything black for me though, even with day and night set to dark

With the settings page is there any js errors (inspect look at console) or php errors? `/var/log/phplog`

**Comment by phyzical** [comment]
Have fixed the settings page issue, just need to workout how to enable this "black" theme

**Comment by phyzical** [comment]
Alright found the setting your talking about, will have to workout how to mimic the theme settings into these iframes

**Comment by phyzical** [comment]
@benfishbus i decided to just hardcode it to white for now to avoid various theme issues
