### ISSUE TITLE
plugin: bad file MD5:

### ISSUE THREAD

**Issue by ssersh** [phyzical/docker.versions#8]
plugin: installing: docker.versions.plg
Executing hook script: pre_plugin_checks
plugin: downloading: docker.versions.plg ... done

plugin: downloading: docker.versions-2024.10.01.txz ... done

plugin: bad file MD5: /boot/config/plugins/docker.versions/docker.versions-2024.10.01.txz
Executing hook script: gui_search_post_hook.sh
Executing hook script: post_plugin_checks

**Comment by phyzical** [comment]
@ssersh thanks looking now... the CI seems to have ignore the plg file for some reason

**Comment by phyzical** [comment]
@ssersh okay should be resolve now on the latest version could you please give it a try?
